import "@/app/css/globals.css";

import Header from "@/app/components/layout/Header";
import type { Metadata } from "next";
import Providers from "@/app/ReactQueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-white dark:bg-black">
        <Header />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
